units = [
    {
        "name": "United States Dollar",
        "root_unit": "USD^1",
        "conversion_factor": 1,
        "symbol": "USD",
        "alternative_symbols": ["$", "﹩", "＄"],
    },
    {
        "name": "Australian Dollar",
        "root_unit": "AUD^1",
        "conversion_factor": 1,
        "symbol": "AUD",
        "alternative_symbols": ["$", "﹩", "＄"],
    },
    {
        "name": "United States Cent",
        "root_unit": "USD^1",
        "conversion_factor": 0.01,
        "symbol": "USC",
        "alternative_symbols": ["¢", "￠"],
    },
    {
        "name": "Great British Pound",
        "root_unit": "GPB^1",
        "conversion_factor": 1,
        "symbol": "GPB",
        "alternative_symbols": ["£", "￡"],
    },
    {
        "name": "Japanese Yen",
        "root_unit": "JPY^1",
        "conversion_factor": 1,
        "symbol": "JPY",
        "alternative_symbols": ["¥", "￥"],
    },
    {
        "name": "Armenian Dram",
        "root_unit": "AMD^1",
        "conversion_factor": 1,
        "symbol": "AMD",
        "alternative_symbols": ["֏"],
    },
    {
        "name": "Afghani Afghani",
        "root_unit": "AFN^1",
        "conversion_factor": 1,
        "symbol": "AFN",
        "alternative_symbols": ["؋"],
    },
    {
        "name": "Bengali Taka",
        "root_unit": "BDT^1",
        "conversion_factor": 1,
        "symbol": "BDT",
        "alternative_symbols": ["৳"],
    },
    {
        "name": "Bengali Rupee",
        "root_unit": "৲^1",
        "conversion_factor": 1,
        "symbol": "৲",
        "alternative_symbols": [],
    },
    {
        "name": "Bengali Ganda",
        "root_unit": "৻^1",
        "conversion_factor": 1,
        "symbol": "৻",
        "alternative_symbols": [],
    },
    {
        "name": "Gujarati Rupee",
        "root_unit": "૱^1",
        "conversion_factor": 1,
        "symbol": "૱",
        "alternative_symbols": [],
    },
    {
        "name": "Indian Rupee",
        "root_unit": "INR^1",
        "conversion_factor": 1,
        "symbol": "INR",
        "alternative_symbols": ["௹"],
    },
    {
        "name": "Sri Lankan Rupee",
        "root_unit": "LKR^1",
        "conversion_factor": 1,
        "symbol": "LKR",
        "alternative_symbols": ["௹"],
    },
    {
        "name": "Thai Baht",
        "root_unit": "THB^1",
        "conversion_factor": 1,
        "symbol": "THB",
        "alternative_symbols": ["฿"],
    },
    {
        "name": "Khmer Riel",
        "root_unit": "KHR^1",
        "conversion_factor": 1,
        "symbol": "KHR",
        "alternative_symbols": ["៛"],
    },
    {
        "name": "Costa Rican Colon",
        "root_unit": "CRC^1",
        "conversion_factor": 1,
        "symbol": "CRC",
        "alternative_symbols": ["₡"],
    },
    {
        "name": "Brazilian Cruzeiro Real",
        "root_unit": "BRL^1",
        "conversion_factor": 1,
        "symbol": "BRL",
        "alternative_symbols": ["₢"],
    },
    {
        "name": "French Franc",
        "root_unit": "₣^1",
        "conversion_factor": 1,
        "symbol": "₣",
        "alternative_symbols": [],
    },
    {
        "name": "Turkish Lira",
        "root_unit": "TRL^1",
        "conversion_factor": 1,
        "symbol": "TRL",
        "alternative_symbols": ["₤", "₺"],
    },
    {
        "name": "United States Mill",
        "root_unit": "USD^1",
        "conversion_factor": 0.001,
        "symbol": "₥",
        "alternative_symbols": [],
    },
    {
        "name": "Nigerian Naira",
        "root_unit": "NGN^1",
        "conversion_factor": 1,
        "symbol": "NGN",
        "alternative_symbols": ["₦"],
    },
    {
        "name": "Spanish Peseta",
        "root_unit": "₧^1",
        "conversion_factor": 1,
        "symbol": "₧",
        "alternative_symbols": [],
    },
    {
        "name": "Pakistani Rupee",
        "root_unit": "PKR^1",
        "conversion_factor": 1,
        "symbol": "PKR",
        "alternative_symbols": ["₨"],
    },
    {
        "name": "Korean Won",
        "root_unit": "KRW^1",
        "conversion_factor": 1,
        "symbol": "KRW",
        "alternative_symbols": ["₩", "￦"],
    },
    {
        "name": "New Israeli Shekel",
        "root_unit": "ILS^1",
        "conversion_factor": 1,
        "symbol": "ILS",
        "alternative_symbols": ["₪"],
    },
    {
        "name": "Vietnamese Dong",
        "root_unit": "VND^1",
        "conversion_factor": 1,
        "symbol": "VND",
        "alternative_symbols": ["₫"],
    },
    {
        "name": "European Union Euro",
        "root_unit": "EUR^1",
        "conversion_factor": 1,
        "symbol": "EUR",
        "alternative_symbols": ["€", "₠"],
    },
    {
        "name": "Mongolian Tugrik",
        "root_unit": "MNT^1",
        "conversion_factor": 1,
        "symbol": "MNT",
        "alternative_symbols": ["₮"],
    },
    {
        "name": "Greek Drachma",
        "root_unit": "₯^1",
        "conversion_factor": 1,
        "symbol": "₯",
        "alternative_symbols": [],
    },
    {
        "name": "German Pfennig",
        "root_unit": "₰^1",
        "conversion_factor": 1,
        "symbol": "₰",
        "alternative_symbols": [],
    },
    {
        "name": "Philippine Peso",
        "root_unit": "PHP^1",
        "conversion_factor": 1,
        "symbol": "PHP",
        "alternative_symbols": ["₱"],
    },
    {
        "name": "Paraguayan Guarani",
        "root_unit": "PYG^1",
        "conversion_factor": 1,
        "symbol": "PYG",
        "alternative_symbols": ["₲"],
    },
    {
        "name": "Argentine Austral",
        "root_unit": "₳^1",
        "conversion_factor": 1,
        "symbol": "₳",
        "alternative_symbols": [],
    },
    {
        "name": "Ukranian Hyvina",
        "root_unit": "UAH^1",
        "conversion_factor": 1,
        "symbol": "UAH",
        "alternative_symbols": ["₴"],
    },
    {
        "name": "Ghanaian Cedi",
        "root_unit": "GHS^1",
        "conversion_factor": 1,
        "symbol": "GHS",
        "alternative_symbols": ["₵"],
    },
    {
        "name": "French Livre",
        "root_unit": "₶^1",
        "conversion_factor": 1,
        "symbol": "₶",
        "alternative_symbols": [],
    },
    {
        "name": "International Spesmilo",
        "root_unit": "₷^1",
        "conversion_factor": 1,
        "symbol": "₷",
        "alternative_symbols": [],
    },
    {
        "name": "Kazakhstani Tenge",
        "root_unit": "KZT^1",
        "conversion_factor": 1,
        "symbol": "KZT",
        "alternative_symbols": ["₸"],
    },
    {
        "name": "Nordic Mark",
        "root_unit": "₻^1",
        "conversion_factor": 1,
        "symbol": "₻",
        "alternative_symbols": [],
    },
    {
        "name": "Azerbaijani Manat",
        "root_unit": "AZN^1",
        "conversion_factor": 1,
        "symbol": "AZN",
        "alternative_symbols": ["₼"],
    },
    {
        "name": "Russian Ruble",
        "root_unit": "RUB^1",
        "conversion_factor": 1,
        "symbol": "RUB",
        "alternative_symbols": ["₽"],
    },
    {
        "name": "Georgian Lari",
        "root_unit": "GEL^1",
        "conversion_factor": 1,
        "symbol": "GEL",
        "alternative_symbols": ["₾"],
    },
    {
        "name": "Bitcoin",
        "root_unit": "BTC^1",
        "conversion_factor": 1,
        "symbol": "BTC",
        "alternative_symbols": ["₿"],
    },
    {
        "name": "Iranian Rial",
        "root_unit": "IRR^1",
        "conversion_factor": 1,
        "symbol": "IRR",
        "alternative_symbols": ["﷼"],
    },
]
